version: "3.9"

services:
  app:
    build: .
    restart: always
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=ledger
      - DB_HOST=db
    depends_on:
      - db
    ports:
      - "8080:3000"

  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=ledger
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  prometheus:
    image: prom/prometheus:v2.41.0
    user: root
    volumes:
      - "./prometheus/:/etc/prometheus"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
    ports:
      - "9090:9090"

#  grafana:
#    image: grafana/grafana
#    user: root
#    ports:
#      - "3000:3000"
#    volumes:
#      - "./grafana/:/var/lib/grafana"
#    environment:
#      - GF_SECURITY_ADMIN_PASSWORD=password
#      - GF_USERS_ALLOW_SIGN_UP=false